package com.example.nutry.data.repository

import com.example.nutry.data.dao.TrackDao
import com.example.nutry.data.dao.DishDao
import com.example.nutry.data.entities.TrackEntry
import kotlinx.coroutines.flow.Flow
import java.util.Date

class TrackRepository(
    private val trackDao: TrackDao,
    private val dishDao: DishDao
) {
    
    fun getAllTrackEntries(): Flow<List<TrackEntry>> = trackDao.getAllTrackEntries()
    
    fun getUserInitiatedTrackEntries(): Flow<List<TrackEntry>> = trackDao.getUserInitiatedTrackEntries()
    
    suspend fun getTrackEntryById(id: Int): TrackEntry? = trackDao.getTrackEntryById(id)
    
    suspend fun getTrackEntriesByDish(dishId: Int): List<TrackEntry> = 
        trackDao.getTrackEntriesByDish(dishId)
    
    suspend fun getTrackEntriesByIngredient(ingredientId: Int): List<TrackEntry> = 
        trackDao.getTrackEntriesByIngredient(ingredientId)
    
    suspend fun getLastDishConsumption(dishId: Int, fromDate: Date): TrackEntry? = 
        trackDao.getLastDishConsumption(dishId, fromDate)
    
    suspend fun getLastIngredientConsumption(ingredientId: Int, fromDate: Date): TrackEntry? = 
        trackDao.getLastIngredientConsumption(ingredientId, fromDate)
    
    suspend fun insertTrackEntry(trackEntry: TrackEntry): Long {
        val id = trackDao.insertTrackEntry(trackEntry)
        
        // If tracking a dish, create individual ingredient entries
        if (trackEntry.dishId != null) {
            val ingredientIds = dishDao.getIngredientIdsByDish(trackEntry.dishId!!)
            ingredientIds.forEach { ingredientId ->
                val ingredientTrackEntry = TrackEntry(
                    dishId = null,
                    ingredientId = ingredientId,
                    consumedAt = trackEntry.consumedAt,
                    quantity = trackEntry.quantity,
                    isAutoGenerated = true,
                    parentTrackId = id.toInt()
                )
                trackDao.insertTrackEntry(ingredientTrackEntry)
            }
        }
        
        return id
    }
    
    suspend fun updateTrackEntry(trackEntry: TrackEntry) = trackDao.updateTrackEntry(trackEntry)
    
    suspend fun deleteTrackEntry(trackEntry: TrackEntry) {
        // First delete auto-generated child entries if this is a parent dish entry
        if (trackEntry.dishId != null && !trackEntry.isAutoGenerated) {
            trackDao.deleteAutoGeneratedEntriesByParent(trackEntry.id)
        }
        // Then delete the main entry
        trackDao.deleteTrackEntry(trackEntry)
    }
    
    suspend fun deleteTrackEntryById(id: Int) {
        // Get the entry to check if it's a parent dish entry
        val entry = trackDao.getTrackEntryById(id)
        if (entry?.dishId != null && !entry.isAutoGenerated) {
            trackDao.deleteAutoGeneratedEntriesByParent(id)
        }
        // Then delete the main entry
        trackDao.deleteTrackEntryById(id)
    }
}